# Generated by Django 5.1.5 on 2025-06-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expense", "0002_alter_expense_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    ("SPORT", "Sport"),
                    ("ENTERTAINMENT", "Entertainment"),
                    ("TRAVELING", "Traveling"),
                    ("EATING OUT", "Eating Out"),
                ],
                max_length=20,
            ),
        ),
    ]
